name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.head_commit.message, 'release/') || contains(github.event.head_commit.message, 'chore: bump version to')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GIT_PAT_TOKEN }}

      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions [Bot]"

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Run linting
        run: npm run lint:check

      - name: Run formatting check
        run: npm run format:check

      - name: Build package
        run: npm run build:clean

      - name: Extract version from commit message
        id: extract-version
        run: |
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          if [[ "$COMMIT_MSG" =~ chore:\ bump\ version\ to\ ([0-9]+\.[0-9]+\.[0-9]+) ]]; then
            NEW_VERSION="${BASH_REMATCH[1]}"
            echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
            echo "Extracted version: $NEW_VERSION"
          else
            echo "Could not extract version from commit message: $COMMIT_MSG"
            exit 1
          fi

      - name: Update package.json version
        run: |
          NEW_VERSION="${{ steps.extract-version.outputs.new_version }}"
          echo "Updating package.json to version: $NEW_VERSION"
          npm version $NEW_VERSION --no-git-tag-version
          git add package.json package-lock.json
          git commit -m "chore: update package.json to v$NEW_VERSION" || echo "No changes to commit"
          git push origin main

      - name: Generate changelog
        id: changelog
        run: |
          NEW_VERSION="${{ steps.extract-version.outputs.new_version }}"
          
          # Get commits since last tag
          if git tag --list | grep -q "v"; then
            LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
            if [ -n "$LAST_TAG" ]; then
              CHANGELOG=$(git log --pretty=format:"- %s" ${LAST_TAG}..HEAD | grep -v "chore: bump version" | grep -v "chore: update package.json")
            else
              CHANGELOG=$(git log --pretty=format:"- %s" | grep -v "chore: bump version" | grep -v "chore: update package.json")
            fi
          else
            CHANGELOG=$(git log --pretty=format:"- %s" | grep -v "chore: bump version" | grep -v "chore: update package.json")
          fi
          
          # If changelog is empty, add a default message
          if [ -z "$CHANGELOG" ]; then
            CHANGELOG="- Initial release"
          fi
          
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Update CHANGELOG.md
        run: |
          NEW_VERSION="${{ steps.extract-version.outputs.new_version }}"
          TODAY=$(date +"%Y-%m-%d")
          CHANGELOG_CONTENT="${{ steps.changelog.outputs.changelog }}"

          # Create new changelog entry
          NEW_ENTRY="## [$NEW_VERSION] - $TODAY\n\n$CHANGELOG_CONTENT\n\n---\n\n"

          # Update or create CHANGELOG.md
          if [ -f "CHANGELOG.md" ]; then
            # Insert new entry after title/header
            if grep -q "^# " CHANGELOG.md; then
              # Has title, insert after first line
              {
                head -n 1 CHANGELOG.md
                echo ""
                echo -e "$NEW_ENTRY"
                tail -n +2 CHANGELOG.md
              } > CHANGELOG_temp.md && mv CHANGELOG_temp.md CHANGELOG.md
            else
              # No title, prepend entry
              {
                echo -e "$NEW_ENTRY"
                cat CHANGELOG.md
              } > CHANGELOG_temp.md && mv CHANGELOG_temp.md CHANGELOG.md
            fi
          else
            # Create new CHANGELOG.md
            {
              echo "# Changelog"
              echo ""
              echo "All notable changes to this project will be documented in this file."
              echo ""
              echo -e "$NEW_ENTRY"
            } > CHANGELOG.md
          fi

          # Commit changelog if there are changes
          if ! git diff --quiet CHANGELOG.md; then
            git add CHANGELOG.md
            git commit -m "docs: update CHANGELOG.md for v$NEW_VERSION"
            git push origin main
          fi

      - name: Create git tag
        run: |
          NEW_VERSION="${{ steps.extract-version.outputs.new_version }}"
          git tag -a "v$NEW_VERSION" -m "Release v$NEW_VERSION"
          git push origin "v$NEW_VERSION"

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.extract-version.outputs.new_version }}
          name: Release v${{ steps.extract-version.outputs.new_version }}
          body: |
            🚀 **Release v${{ steps.extract-version.outputs.new_version }}**

            ${{ steps.changelog.outputs.changelog }}

            ## 📦 Installation
            ```bash
            npm install genius-bridge-sdk@latest
            # or
            npm install genius-bridge-sdk@${{ steps.extract-version.outputs.new_version }}
            ```
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_PAT_TOKEN }}

      - name: Create PR to sync main back to develop
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GIT_PAT_TOKEN }}
          script: |
            try {
              await github.rest.repos.getBranch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch: 'develop'
              });
              
              const pr = await github.rest.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: 'Sync main to develop after release v${{ steps.extract-version.outputs.new_version }}',
                head: 'main',
                base: 'develop',
                body: [
                  '🔄 **Sync Release v${{ steps.extract-version.outputs.new_version }} to Develop**',
                  '',
                  'This PR syncs the release changes from `main` back to `develop` to keep both branches in sync.',
                  '',
                  '## 🚀 Release v${{ steps.extract-version.outputs.new_version }}',
                  '',
                  '${{ steps.changelog.outputs.changelog }}',
                  '',
                  '## Why This PR?',
                  'After a release, `main` contains the tagged version and updated changelog, but `develop` is behind. This sync ensures:',
                  '- Future development starts from the correct version',
                  '- CHANGELOG.md is up to date on develop',
                  '- No version conflicts in future releases',
                  '- Clean GitFlow branch management',
                  '',
                  '## Next Steps',
                  '1. Review and merge this PR to sync develop',
                  '2. Continue development on develop branch from the new version',
                  '',
                  '---',
                  '*This PR was automatically created by the release workflow.*'
                ].join('\n')
              });
              
              console.log(\`Created sync PR #\${pr.data.number}: \${pr.data.html_url}\`);
              
            } catch (error) {
              console.log('Error creating sync PR:', error.message);
            }
